# Generated by Django 5.2.1 on 2025-05-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='banner',
            new_name='image',
        ),
    ]
